### ISSUE TITLE
usage of spirit V2 with boost 1.87: 'boost::endian::order::enum_type' has not been declared

### ISSUE THREAD

**Issue by abenbelg** [boostorg/spirit#847]
Hello, 
I am trying to use boost **spirit v2** with boost **1.87**. I am getting the following errors when trying do to so: 

Example code that is not working with boost **1.87**: 
```
inline bool TryParseInt(const char *pcDatalineArg, int *pi)
{
    namespace qi = boost::spirit::qi;
    namespace ascii = boost::spirit::ascii;

    if (!pcDatalineArg)
        return false;

    const auto length = strlen(pcDatalineArg);
    return qi::phrase_parse(pcDatalineArg, pcDatalineArg + length, qi::int_ >> qi::eoi, ascii::blank, *pi);
}
```

**error messages:** 
```
/my_project/ThirdParty/boost/1_87_0/include/boost/spirit/home/qi/binary/binary.hpp:198:37: error: 'boost::endian::order::enum_type' has not been declared 
2.   198 |         template <BOOST_SCOPED_ENUM(boost::endian::order) bits> 
     |                                     ^~~~~ 
/my_project/ThirdParty/boost/1_87_0/include/boost/core/scoped_enum.hpp:169:44: note: in definition of macro 'BOOST_SCOPED_ENUM_NATIVE' 
 169 | #define BOOST_SCOPED_ENUM_NATIVE(EnumType) EnumType::enum_type 
     |                                            ^~~~~~~~ 
/my_project/ThirdParty/boost/1_87_0/include/boost/spirit/home/qi/binary/binary.hpp:198:19: note: in expansion of macro 'BOOST_SCOPED_ENUM' 
 198 |         template <BOOST_SCOPED_ENUM(boost::endian::order) bits> 
     |                   ^~~~~~~~~~~~~~~~~ 
/my_project/ThirdParty/boost/1_87_0/include/boost/spirit/home/qi/binary/binary.hpp:221:45: error: 'boost::endian::order::enum_type' has not been declared 
```

When reading the documentation I don't see warnings about spirit v2 not being supported with boost 1.87. 

How can I solve this issue with boost 1.87 ? 

**Note:**
with boost **1.71** I am not getting any error of this kind, it is compiling fine.

**Comment by djowel** [comment]
Can you do a Git bisect so we can figure out what commit caused this?

**Comment by abenbelg** [comment]
Narrowed down the issue, using this tag when compiling leads to the error that I listed above 
-DBOOST_NO_CXX11_SCOPED_ENUMS

This issue can be closed or tracked down.
Thanks

**Comment by djowel** [comment]
I see. I'm glad you figured out a solution.
