### PR TITLE
X3: Fix `unused_type` attribute case in `parse_into_container`

### PR DESCRIPTION
**Pull request by Kojoley**
Passing `unused_type` attribute to `parse_into_container_impl::call` produces a compilation error (clang: https://travis-ci.org/Kojoley/spirit/jobs/298783103 gcc: https://travis-ci.org/Kojoley/spirit/jobs/298783104).

The issue was introduced in 379413a50c93539aa432fa9f9fc94fec1d6aa60d.

While the fix restores x3 test suite (checked on msvc, gcc, clang) I am not quite sure it is the right solution. @djowel please, review the fix.

### CODE REVIEW

**Comment by djowel** [comment]
Yes, you are doing it right. A "fix" without a test case is always suspicious.

**Comment by Kojoley** [comment]
Without this fix current test suite does not pass (compile error in `confix` test, see logs above). You want me to come up with a new one?

**Comment by djowel** [comment]
What "new one" do you have in mind?

**Comment by djowel** [comment]
Anyway, I think this is correct as far as I can tell.

**Comment by Kojoley** [comment]
That does not exist (or disabled) in current test suite and targets particular problem.
