### PR TITLE
X3.Tests: Add c++14 feature checks

### LINKED ISSUE #301: X3 doesn't compile on g++ 4.8 cxxstd=11
https://travis-ci.org/boostorg/boost/jobs/308195225

```
./boost/spirit/home/x3/support/context.hpp:28:18: error: expected primary-expression before ‘auto’
         decltype(auto) get(ID_ id) const
                  ^
```

These tests should probably be guarded by `requires`.

Also,

```
In file included from libs/spirit/test/x3/x3_variant.cpp:9:
./boost/spirit/home/x3/support/ast/variant.hpp:134:50: error: no template named 'remove_reference_t' in namespace 'std'; did you mean simply 'remove_reference_t'?
                                                ,std::remove_reference_t<T>
```

Looks like X3 wants C++14.

### PR DESCRIPTION
**Pull request by Kojoley**
Closes #301

attn @pdimov

### CODE REVIEW

**Comment by pdimov** [comment]
Looks good.

**Comment by pdimov** [comment]
Travis green now: https://travis-ci.org/boostorg/boost/builds/308911871
Appveyor msvc-14.0 doesn't like x3 at two places: https://ci.appveyor.com/project/boostorg/boost/build/1.0.4920-develop

But you probably know that already.
